"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee de la variable de entorno DJANGO_SECRET_KEY (ver .env / .env.example).
# El valor de respaldo solo existe para que el proyecto arranque en un clon
# nuevo sin configurar nada; en cualquier despliegue real hay que definir
# DJANGO_SECRET_KEY con una clave propia.
_SECRET_KEY_INSEGURA_POR_DEFECTO = 'django-insecure-*+j_=n16)cxu3ktfv#ws!ab59#=*9x6q)&@ewd)+7zi=etfi23'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _SECRET_KEY_INSEGURA_POR_DEFECTO)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

if not DEBUG and SECRET_KEY == _SECRET_KEY_INSEGURA_POR_DEFECTO:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DJANGO_DEBUG=False pero no se definió DJANGO_SECRET_KEY. "
        "Generar una clave propia (ver .env.example) antes de desplegar a producción."
    )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'narraciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'narraciones.middleware.JardinActivoMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# En desarrollo usa SQLite (no requiere configuración). En producción, definir
# DATABASE_URL (por ejemplo postgres://usuario:clave@host:5432/nombre_db) para
# usar PostgreSQL, necesario en cuanto haya más de una institución usando la
# app al mismo tiempo.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # RF-01: la contraseña debe tener un mínimo de 10 caracteres.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = 'narraciones:login'
LOGIN_REDIRECT_URL = 'narraciones:menu'
LOGOUT_REDIRECT_URL = 'narraciones:landing'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # debe ir primero: bloquea antes de validar credenciales
    'django.contrib.auth.backends.ModelBackend',
]

# Protección contra fuerza bruta (django-axes): datos sensibles de menores
# ameritan bloquear intentos repetidos de adivinar una contraseña.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas de bloqueo tras superar el límite
AXES_LOCKOUT_PARAMETERS = ['ip_address', 'username']
AXES_LOCKOUT_TEMPLATE = 'narraciones/cuenta_bloqueada.html'
AXES_RESET_ON_SUCCESS = True

# Sesión: expira por inactividad y al cerrar el navegador, pensado para
# dispositivos compartidos en una institución (tablet/PC de sala).
SESSION_COOKIE_AGE = 60 * 60 * 2  # 2 horas
SESSION_SAVE_EVERY_REQUEST = True  # cada request activo renueva el conteo
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# E-mail: por defecto imprime los correos en la consola del servidor (útil
# para desarrollo). En producción, configurar un proveedor SMTP real con las
# variables EMAIL_* de abajo (ver .env.example).
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-responder@narraciones-interactivas.local')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (pictogramas, portadas de cuentos, etc.): por defecto se guardan en el
# filesystem local, lo cual sirve en desarrollo pero se PIERDE en cada deploy
# en hostings con filesystem efímero (Heroku, Render, Railway). Definir
# USE_S3=True + las variables AWS_* (ver .env.example) para usar almacenamiento
# en la nube (S3 o compatible) antes de ir a producción con usuarios reales.
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'
if USE_S3:
    INSTALLED_APPS.append('storages')

STORAGES = {
    'default': {
        'BACKEND': (
            'storages.backends.s3.S3Storage' if USE_S3
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'sa-east-1')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"}/media/'
else:
    MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Seguridad para producción (se activa automáticamente cuando DJANGO_DEBUG=False)
# https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Necesario detrás de un proxy/balanceador (Render, Railway, etc.) que
    # termina la conexión HTTPS y reenvía por HTTP con esta cabecera.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'DENY'
