# Generated by Django 6.0.3 on 2026-03-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cuerpo_cuento', models.TextField(help_text='Escribe aquí la historia completa')),
                ('categoria_edad', models.CharField(choices=[('3-5', '3 a 5 años'), ('6-8', '6 a 8 años'), ('9-12', '9 a 12 años')], max_length=10)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='cuentos_portadas/')),
                ('imagen_final', models.ImageField(help_text='Imagen que se muestra al terminar', upload_to='finales/')),
            ],
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_identificador', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(upload_to='pictogramas/')),
                ('tipo_imagen', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoNarracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('le_gusto', models.BooleanField()),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narraciones.cuento')),
                ('nino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='narraciones.nino')),
            ],
        ),
        migrations.CreateModel(
            name='Sinonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pictograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinonimos', to='narraciones.pictograma')),
            ],
        ),
    ]
