# Generated by Django 6.1 on 2026-08-17 12:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuento',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Cuento', 'verbose_name_plural': 'Cuentos'},
        ),
        migrations.AlterModelOptions(
            name='nino',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Niño', 'verbose_name_plural': 'Niños'},
        ),
        migrations.AlterModelOptions(
            name='pictograma',
            options={'ordering': ['nombre_identificador'], 'verbose_name': 'Pictograma', 'verbose_name_plural': 'Pictogramas'},
        ),
        migrations.AlterModelOptions(
            name='resultadonarracion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Resultado de Narración', 'verbose_name_plural': 'Resultados de Narraciones'},
        ),
        migrations.AlterModelOptions(
            name='sinonimo',
            options={'ordering': ['palabra'], 'verbose_name': 'Sinónimo', 'verbose_name_plural': 'Sinónimos'},
        ),
        migrations.AddField(
            model_name='cuento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuento',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nino',
            name='institucion_o_sala',
            field=models.CharField(blank=True, help_text='Sala, curso o jardín al que asiste', max_length=100),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadonarracion',
            name='duracion_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo total de lectura/actividad', null=True),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='imagen_final',
            field=models.ImageField(blank=True, help_text='Imagen opcional que se muestra al terminar', null=True, upload_to='finales/'),
        ),
        migrations.AlterField(
            model_name='cuento',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nino',
            name='edad',
            field=models.PositiveSmallIntegerField(help_text='Edad entre 1 y 18 años', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='pictograma',
            name='nombre_identificador',
            field=models.CharField(help_text='Ej: Abuela', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pictograma',
            name='tipo_imagen',
            field=models.CharField(blank=True, choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo'), ('otro', 'Otro')], default='sustantivo', max_length=45),
        ),
        migrations.AlterField(
            model_name='resultadonarracion',
            name='cuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='narraciones.cuento'),
        ),
        migrations.AlterField(
            model_name='resultadonarracion',
            name='le_gusto',
            field=models.BooleanField(help_text='Indica si al niño le gustó la narración'),
        ),
        migrations.AlterField(
            model_name='resultadonarracion',
            name='nino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='narraciones.nino'),
        ),
        migrations.AlterField(
            model_name='sinonimo',
            name='palabra',
            field=models.CharField(db_index=True, help_text='Palabra clave o sinónimo (ej: abuelita)', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='resultadonarracion',
            index=models.Index(fields=['cuento', 'fecha'], name='narraciones_cuento__f721fb_idx'),
        ),
    ]
