# Generated by Django 6.1 on 2026-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0003_nino_dni_nino_domicilio_nino_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictograma',
            name='alerta_contenido',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='revisado',
            field=models.BooleanField(default=False, help_text='Un administrador debe confirmar esto manualmente antes de que el pictograma se use en narraciones (RF-05).', verbose_name='Revisado y apto para menores'),
        ),
        migrations.AddField(
            model_name='pictograma',
            name='validacion_tecnica_ok',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
