# Generated by Django 6.1 on 2026-09-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0004_pictograma_alerta_contenido_pictograma_revisado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadonarracion',
            name='cuento',
            field=models.ForeignKey(blank=True, help_text="Vacío cuando la sesión fue una narración libre (RF-09: 'narrar mi propia historia').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='narraciones.cuento'),
        ),
    ]
