# Generated by Django 6.1 on 2026-09-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0005_alter_resultadonarracion_cuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cuil', models.CharField(blank=True, max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jardín',
                'verbose_name_plural': 'Jardines',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='nino',
            name='jardin',
            field=models.ForeignKey(blank=True, help_text='Institución a la que pertenece; determina quién puede verlo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninos', to='narraciones.jardin'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='jardin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='narraciones.jardin'),
        ),
    ]
