# Generated by Django 6.1 on 2026-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0006_jardin_nino_jardin_perfilusuario_jardin'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='autorizacion_parental',
            field=models.BooleanField(default=False, help_text='Quien da de alta al niño/a confirma contar con la autorización de sus padres o tutores (precondición del CU Alta de Usuario).', verbose_name='Autorización de padres/tutores registrada'),
        ),
        migrations.AddField(
            model_name='nino',
            name='autorizacion_registrada_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
