# Generated by Django 6.1 on 2026-09-11 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0007_nino_autorizacion_parental_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_nino', 'Registró un niño/a'), ('editar_nino', 'Modificó datos de un niño/a'), ('eliminar_nino', 'Eliminó a un niño/a'), ('exportar_pdf', 'Exportó un informe en PDF')], max_length=30)),
                ('detalle', models.CharField(blank=True, help_text='Ej: nombre y DNI del niño/a afectado', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('jardin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='narraciones.jardin')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
