# Generated by Django 6.1 on 2026-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0008_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardin',
            name='activo',
            field=models.BooleanField(default=True, help_text='Una institución que se autoregistra queda inactiva hasta que un administrador la aprueba; mientras tanto sus usuarios no pueden usar la aplicación.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='jardin',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_admin_jardin',
            field=models.BooleanField(default=False, help_text='Puede gestionar los demás usuarios (docentes) de su jardín, además de niños y sesiones.', verbose_name='Administrador de la institución'),
        ),
    ]
