# Generated by Django 6.1 on 2026-09-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0009_jardin_activo_jardin_aprobado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='limite_logins_demo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Si se completa, esta cuenta queda bloqueada despues de iniciar sesion esta cantidad de veces. Pensado para compartir un usuario de demostracion a varios prospectos sin que se use indefinidamente. Vacio = sin límite.', null=True, verbose_name='Límite de inicios de sesión (demo)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='logins_demo_usados',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
