# Generated by Django 6.1 on 2026-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narraciones', '0010_perfilusuario_limite_logins_demo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear_nino', 'Registró un niño/a'), ('editar_nino', 'Modificó datos de un niño/a'), ('eliminar_nino', 'Eliminó a un niño/a'), ('exportar_pdf', 'Exportó un informe en PDF'), ('importar_ninos_csv', 'Importó niños/as por CSV')], max_length=30),
        ),
    ]
